### ISSUE TITLE
Erroneous area: 1: 1.6em + 0.75rem2px

### ISSUE THREAD

**Issue by pauubach** [jeremykenedy/laravel-auth#319]
Hi,
First of all, thanks for your work. It's an awesome user auth start for any project.

 I'm on Windows 10. Laravel 6. Yarn 1.19.1. Tried with npm 6.11.3.

Trying to run in production 
yarn run production 
npm run production

I get errors in CSS:

JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 1.6em + 0.75rem2px
^...........^
    at C:\css\app.css:2329:3
    at Object.parseError (C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\parser.js:1164:15)
    at Object.lexer_parseError [as parseError] (C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\parser.js:2297:44)
    at Object.lexer_next [as next] (C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\parser.js:3292:22)
    at Object.lexer_fastLex [as fastLex] (C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\parser.js:3367:18)
    at fastLex (C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\parser.js:1567:27)
    at Parser.parse (C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\parser.js:1641:30)
    at C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\lib\transform.js:30:30
    at walk (C:\laragon\www\inconclusos\node_modules\postcss-value-parser\lib\walk.js:19:7)
    at ValueParser.walk (C:\laragon\www\inconclusos\node_modules\postcss-value-parser\lib\index.js:18:3)
    at transformValue (C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\lib\transform.js:24:50)
    at _default (C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\lib\transform.js:59:100)
    at C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\index.js:25:51
    at C:\laragon\www\inconclusos\node_modules\postcss\lib\container.js:135:18
    at Rule.each (C:\laragon\www\inconclusos\node_modules\postcss\lib\container.js:101:16)
    at Rule.walk (C:\laragon\www\inconclusos\node_modules\postcss\lib\container.js:131:17)
    at C:\laragon\www\inconclusos\node_modules\postcss\lib\container.js:148:24
    at Root.each (C:\laragon\www\inconclusos\node_modules\postcss\lib\container.js:101:16)
    at Root.walk (C:\laragon\www\inconclusos\node_modules\postcss\lib\container.js:131:17)
    at C:\laragon\www\inconclusos\node_modules\postcss-calc\dist\index.js:23:9
    at initializePlugin (C:\laragon\www\inconclusos\node_modules\cssnano\dist\index.js:31:51)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jeremykenedy** [comment]
I’m unable to relocate the issue, it may be something with your file system.

**Comment by pauubach** [comment]
npm run watch and dev runs fine, but they are making a css with problems: 
there are 11 places where rem is followed by 2px. 
Example:
.form-control {
  display: block;
  width: 100%;
  height: calc(1.6em + 0.75rem2px);
...


.form-control-sm {
  height: calc(1.5em + 0.5rem2px);
  padding: 0.25rem 0.5rem;
  font-size: 0.7875rem;
  line-height: 1.5;
  border-radius: 0.2rem;
}

.form-control-lg {
  height: calc(1.5em + 1rem2px);
  padding: 0.5rem 1rem;
  font-size: 1.125rem;
  line-height: 1.5;
  border-radius: 0.3rem;
}

**Comment by jeremykenedy** [comment]
That would be a core issue with Bootstrap 4 then. That SCSS comes from

https://github.com/jeremykenedy/laravel-auth/blob/master/package.json#L14
https://github.com/jeremykenedy/laravel-auth/blob/master/resources/assets/sass/app.scss#L8

node_modules/bootstrap/scss/_forms.scss lines 137-139

**Comment by rijoshrc** [comment]
I tried after updating my bootstrap version 4.4.1 (latest) and fixed this issue.
